export type SimulationTopic = {
  id: string;
  category: string;
  title: string;
  titleJa: string;
  emoji: string;
  description: string;
  partnerRole: string;
  partnerName: string;
  situation: string;
  firstMessage: string;
  characterGender: "male" | "female";
  sceneBg: string;
  sceneEmoji: string;
  chatBgColor: string;
  chatBgImage: string;
};

export const simulationTopics: SimulationTopic[] = [
  {
    id: "hotel-checkin",
    category: "海外旅行",
    title: "Hotel Check-in",
    titleJa: "ホテルチェックイン",
    emoji: "🏨",
    description: "ホテルに到着してチェックインする練習",
    partnerRole: "hotel front desk staff",
    partnerName: "Front Desk",
    situation: "You just arrived at a hotel and need to check in.",
    firstMessage: "Welcome to Grand Hotel! Do you have a reservation?",
    characterGender: "female",
    sceneBg: "bg-gradient-to-b from-blue-400 to-blue-600",
    sceneEmoji: "🏨",
    chatBgColor: "#eff6ff",
    chatBgImage: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=60",
  },
  {
    id: "hotel-checkout",
    category: "海外旅行",
    title: "Hotel Check-out",
    titleJa: "ホテルチェックアウト",
    emoji: "🛎️",
    description: "ホテルをチェックアウトする練習",
    partnerRole: "hotel front desk staff",
    partnerName: "Front Desk",
    situation: "You're checking out of your hotel.",
    firstMessage: "Good morning! Are you checking out today?",
    characterGender: "male",
    sceneBg: "bg-gradient-to-b from-blue-300 to-blue-500",
    sceneEmoji: "🛎️",
    chatBgColor: "#eff6ff",
    chatBgImage: "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800&q=60",
  },
  {
    id: "airport-ca",
    category: "海外旅行",
    title: "On the Airplane",
    titleJa: "機内でCAさんとのやり取り",
    emoji: "✈️",
    description: "飛行機の中でCAさんと会話する練習",
    partnerRole: "flight attendant",
    partnerName: "Flight Attendant",
    situation: "You're on an airplane and the flight attendant is serving.",
    firstMessage: "Would you like something to drink?",
    characterGender: "female",
    sceneBg: "bg-gradient-to-b from-sky-300 to-sky-500",
    sceneEmoji: "✈️",
    chatBgColor: "#f0f9ff",
    chatBgImage: "https://images.unsplash.com/photo-1436491865332-7a61a109db05?w=800&q=60",
  },
  {
    id: "immigration",
    category: "海外旅行",
    title: "Immigration",
    titleJa: "入国審査",
    emoji: "🛂",
    description: "空港の入国審査を通過する練習",
    partnerRole: "immigration officer",
    partnerName: "Officer",
    situation: "You're going through immigration at the airport.",
    firstMessage: "Passport, please. What's the purpose of your visit?",
    characterGender: "male",
    sceneBg: "bg-gradient-to-b from-blue-700 to-blue-900",
    sceneEmoji: "🛂",
    chatBgColor: "#eef2ff",
    chatBgImage: "https://images.unsplash.com/photo-1529074963764-98f45c47344b?w=800&q=60",
  },
  {
    id: "cafe-order",
    category: "海外旅行",
    title: "Cafe Order",
    titleJa: "カフェでオーダー",
    emoji: "☕",
    description: "カフェで飲み物を注文する練習",
    partnerRole: "barista at a coffee shop",
    partnerName: "Barista",
    situation: "You're ordering at a cafe.",
    firstMessage: "Hi there! What can I get for you today?",
    characterGender: "female",
    sceneBg: "bg-gradient-to-b from-amber-600 to-amber-800",
    sceneEmoji: "☕",
    chatBgColor: "#fffbeb",
    chatBgImage: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=800&q=60",
  },
  {
    id: "restaurant-order",
    category: "海外旅行",
    title: "Restaurant Order",
    titleJa: "レストランでオーダー",
    emoji: "🍽️",
    description: "レストランで食事を注文する練習",
    partnerRole: "waiter at a restaurant",
    partnerName: "Waiter",
    situation: "You're ordering food at a restaurant.",
    firstMessage: "Good evening! Here's the menu. Are you ready to order, or do you need a moment?",
    characterGender: "male",
    sceneBg: "bg-gradient-to-b from-red-400 to-red-600",
    sceneEmoji: "🍽️",
    chatBgColor: "#fef2f2",
    chatBgImage: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&q=60",
  },
  {
    id: "directions",
    category: "海外旅行",
    title: "Asking for Directions",
    titleJa: "道案内",
    emoji: "🗺️",
    description: "道に迷って現地の人に道を聞く練習",
    partnerRole: "friendly local person on the street",
    partnerName: "Local",
    situation: "You're lost and asking a local for directions.",
    firstMessage: "Hey! You look a little lost. Can I help you find something?",
    characterGender: "male",
    sceneBg: "bg-gradient-to-b from-green-400 to-green-600",
    sceneEmoji: "🗺️",
    chatBgColor: "#f0fdf4",
    chatBgImage: "https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=800&q=60",
  },
  {
    id: "taxi",
    category: "海外旅行",
    title: "Taking a Taxi",
    titleJa: "タクシーに乗る",
    emoji: "🚕",
    description: "タクシーに乗って行き先を伝える練習",
    partnerRole: "taxi driver",
    partnerName: "Driver",
    situation: "You're getting into a taxi.",
    firstMessage: "Hey, where are you headed?",
    characterGender: "male",
    sceneBg: "bg-gradient-to-b from-yellow-300 to-yellow-500",
    sceneEmoji: "🚕",
    chatBgColor: "#fefce8",
    chatBgImage: "https://images.unsplash.com/photo-1549317661-bd32c8ce0afa?w=800&q=60",
  },
  {
    id: "first-meeting",
    category: "日常会話",
    title: "Meeting Someone New",
    titleJa: "初対面の人との会話",
    emoji: "👋",
    description: "パーティーで初めて会う人と自己紹介する練習",
    partnerRole: "someone you're meeting for the first time at a party",
    partnerName: "Alex",
    situation: "You're at a party and meeting someone new.",
    firstMessage: "Hey! I don't think we've met before. I'm Alex! What's your name?",
    characterGender: "female",
    sceneBg: "bg-gradient-to-b from-pink-300 to-pink-500",
    sceneEmoji: "🎉",
    chatBgColor: "#fdf2f8",
    chatBgImage: "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=800&q=60",
  },
  {
    id: "second-meeting",
    category: "日常会話",
    title: "Meeting Again",
    titleJa: "2回目に会う人との会話",
    emoji: "😊",
    description: "以前会ったことがある人と再会する練習",
    partnerRole: "someone you met once before at a previous event",
    partnerName: "Alex",
    situation: "You're meeting someone for the second time.",
    firstMessage: "Oh hey! I remember you! We met at that party last month, right? How have you been?",
    characterGender: "female",
    sceneBg: "bg-gradient-to-b from-purple-400 to-purple-600",
    sceneEmoji: "😊",
    chatBgColor: "#faf5ff",
    chatBgImage: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=800&q=60",
  },
  {
    id: "shopping",
    category: "海外旅行",
    title: "Shopping",
    titleJa: "お店で買い物",
    emoji: "🛍️",
    description: "洋服店で買い物をする練習",
    partnerRole: "shop assistant at a clothing store",
    partnerName: "Staff",
    situation: "You're shopping for clothes.",
    firstMessage: "Hi! Welcome! Are you looking for anything in particular?",
    characterGender: "female",
    sceneBg: "bg-gradient-to-b from-pink-400 to-pink-600",
    sceneEmoji: "🛍️",
    chatBgColor: "#fdf2f8",
    chatBgImage: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&q=60",
  },
  {
    id: "fast-food",
    category: "海外旅行",
    title: "Fast Food Order",
    titleJa: "ファストフードで注文",
    emoji: "🍔",
    description: "ファストフード店で注文する練習",
    partnerRole: "fast food cashier",
    partnerName: "Cashier",
    situation: "You're ordering at a fast food restaurant.",
    firstMessage: "Hi! Welcome to Burger Town! What can I get for you?",
    characterGender: "male",
    sceneBg: "bg-gradient-to-b from-orange-400 to-orange-600",
    sceneEmoji: "🍔",
    chatBgColor: "#fff7ed",
    chatBgImage: "https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?w=800&q=60",
  },
];
