export type SoloPracticeTopic = {
  id: string;
  category: string;
  title: string;
  emoji: string;
  description: string;
  modelAnswer: string;
  questionExample: string;
  keywords: string[];
};

export const soloPracticeTopics: SoloPracticeTopic[] = [
  { id: "food-001", category: "食べ物", title: "Korean Food", emoji: "🍜", description: "好きな韓国料理について話す練習", modelAnswer: "I like Korean food. I especially like eating Shin Ramyun with kimchi. It's spicy, but it's really good. I highly recommend it.", questionExample: "What's your favorite Korean food?", keywords: ["Korean food", "kimchi", "spicy", "recommend"] },
  { id: "daily-001", category: "日常", title: "My Morning", emoji: "☀️", description: "朝の様子について話す練習", modelAnswer: "Good morning. I woke up a little late today. I still feel sleepy, but I'm going to do my best. I hope today will be a good day.", questionExample: "How's your morning going?", keywords: ["morning", "sleepy", "wake up", "do my best"] },
  { id: "gym-001", category: "健康・ジム", title: "Gym", emoji: "🏋️", description: "ジムや筋トレについて話す練習", modelAnswer: "I'm at the gym now. I'm training my back today. It's really hard, but I have been pushing myself recently. I feel tired, but I'm proud of myself.", questionExample: "Is there anything you're working hard on these days?", keywords: ["gym", "train", "back", "push myself", "proud"] },
  { id: "health-001", category: "健康・ジム", title: "Diet", emoji: "🥗", description: "ダイエットについて話す練習", modelAnswer: "I've been on a diet recently. I lost a little weight, so I'm really happy. I know it's not easy, but I want to keep going.", questionExample: "Have you been working on any health goals recently?", keywords: ["diet", "lose weight", "keep going", "health"] },
  { id: "animal-001", category: "猫・動物", title: "My Cat", emoji: "🐈", description: "猫やペットについて話す練習", modelAnswer: "I've been into playing with my cat recently. She is so adorable. Her face is beautiful, and everything she does is cute. She always makes me happy.", questionExample: "Do you have anything you've been into recently?", keywords: ["cat", "adorable", "cute", "play with", "happy"] },
  { id: "relax-001", category: "サウナ・リラックス", title: "Sauna", emoji: "🧖", description: "サウナやリラックスについて話す練習", modelAnswer: "I'm going to the sauna tonight. Sauna makes me feel relaxed. When I feel tired, I like to go there and clear my mind.", questionExample: "What makes you feel relaxed?", keywords: ["sauna", "relaxed", "tired", "clear my mind"] },
  { id: "food-002", category: "食べ物", title: "Hotpot", emoji: "🍲", description: "鍋料理について話す練習", modelAnswer: "I'm going to eat hotpot today. I like hotpot because it's healthy and filling. I usually put vegetables, tofu, and meat in it.", questionExample: "What's your favorite ingredient to put in hotpot?", keywords: ["hotpot", "healthy", "filling", "vegetables", "tofu"] },
  { id: "travel-001", category: "旅行", title: "Hawaii", emoji: "🌴", description: "行きたい旅行先について話す練習", modelAnswer: "I really want to go to Hawaii someday. I want to go snorkeling and eat garlic shrimp there. Hawaii is one of the places on my bucket list.", questionExample: "What's your dream destination?", keywords: ["Hawaii", "snorkeling", "garlic shrimp", "bucket list"] },
  { id: "work-001", category: "仕事", title: "Working Hard", emoji: "💻", description: "仕事や努力について話す練習", modelAnswer: "I've been working hard recently. I have a lot of things to do, but I'm trying my best. When my hard work pays off, I feel really happy.", questionExample: "What are you working hard on these days?", keywords: ["work hard", "try my best", "pay off", "happy"] },
  { id: "hobby-001", category: "趣味", title: "YouTube", emoji: "📺", description: "YouTubeや動画について話す練習", modelAnswer: "I uploaded a new video on YouTube today. I worked hard on it, so I hope many people watch it. Making videos is difficult, but it's also fun.", questionExample: "What kind of YouTube videos do you like to watch?", keywords: ["YouTube", "upload", "video", "watch", "fun"] },
  { id: "daily-002", category: "日常", title: "Rainy Day", emoji: "☔", description: "雨の日について話す練習", modelAnswer: "It's raining in my area today. I don't really like rainy days, but I want to enjoy the day anyway. Maybe I'll stay home and relax.", questionExample: "How's the weather in your area?", keywords: ["rain", "rainy day", "stay home", "relax"] },
  { id: "food-003", category: "食べ物", title: "Favorite Drink", emoji: "🍹", description: "好きな飲み物について話す練習", modelAnswer: "I'm drinking hojicha-flavored protein now. It tastes really good. I didn't expect it to be this delicious, so I'm happy.", questionExample: "What's your favorite drink?", keywords: ["drink", "protein", "taste", "delicious"] },
  { id: "daily-003", category: "日常", title: "Haircut", emoji: "💇", description: "髪を切った話をする練習", modelAnswer: "I got my haircut today. It's been a while since I last got a haircut. I feel fresh now, and I like my new hairstyle.", questionExample: "When was the last time you got your haircut?", keywords: ["haircut", "fresh", "hairstyle", "it's been a while"] },
  { id: "shopping-001", category: "日常", title: "Supermarket", emoji: "🛒", description: "スーパーや買い物について話す練習", modelAnswer: "I went to my favorite supermarket today. There were a lot of cheap groceries. I like that place because it's convenient and affordable.", questionExample: "What's your favorite supermarket?", keywords: ["supermarket", "groceries", "cheap", "convenient", "affordable"] },
  { id: "if-001", category: "もしも系", title: "Lottery", emoji: "💰", description: "宝くじが当たったら何をするか話す練習", modelAnswer: "I wish I could win the lottery. If I won one hundred million yen, I would buy two houses. One would be for living, and the other would be for investment.", questionExample: "If you won one hundred million yen, what would you do?", keywords: ["lottery", "win", "one hundred million yen", "house", "investment"] },
  { id: "memory-001", category: "思い出・経験", title: "Scary Experience", emoji: "😱", description: "怖かった経験について話す練習", modelAnswer: "I tried bungee jumping before. It was so scary. I'm glad I tried it once, but I don't want to do it again.", questionExample: "Have you experienced anything scary recently?", keywords: ["scary", "bungee jumping", "experience", "try"] },
  { id: "hobby-002", category: "趣味", title: "Favorite Song", emoji: "🎧", description: "好きな曲について話す練習", modelAnswer: "I'm listening to my favorite song right now. It always makes me feel calm. I like the melody and the lyrics.", questionExample: "What's your favorite song?", keywords: ["song", "music", "calm", "melody", "lyrics"] },
  { id: "relax-002", category: "サウナ・リラックス", title: "Taking a Nap", emoji: "😴", description: "昼寝について話す練習", modelAnswer: "I took a nap yesterday evening. Nothing makes me happier than taking a nap. It helps me feel refreshed.", questionExample: "What makes you the happiest?", keywords: ["nap", "happy", "refreshed", "take a nap"] },
  { id: "work-002", category: "仕事", title: "Job Satisfaction", emoji: "😭", description: "仕事のやりがいについて話す練習", modelAnswer: "Some of my students told me they were happy they took my lessons. That made me really happy. Moments like that make my job feel worthwhile.", questionExample: "What makes your job worthwhile?", keywords: ["student", "lesson", "happy", "worthwhile", "job"] },
  { id: "memory-002", category: "思い出・経験", title: "Live Concert", emoji: "🎤", description: "ライブやコンサートについて話す練習", modelAnswer: "I went to a live concert recently. I was so excited. The music, the lights, and the atmosphere were amazing.", questionExample: "Have you ever been to a live concert?", keywords: ["concert", "excited", "music", "atmosphere", "amazing"] },
];
